### ISSUE TITLE
[joss] Add missing DOI

### ISSUE THREAD

**Issue by sneakers-the-rat** [timothyas/xesn#79]
Part of: https://github.com/openjournals/joss-reviews/issues/7286

Is https://doi.org/10.1017/cbo9780511617652.004 the same as the Lorenz 1996 paper you are citing, or is that a different work? Just want to check to satisfy our very picky DOI checker, close this if those are two different citations.

**Comment by sneakers-the-rat** [comment]
I think [this is the citation for dask](https://proceedings.scipy.org/articles/Majora-7b98e3ed-013)

```
@InProceedings{ matthew_rocklin-proc-scipy-2015,
  author    = { {M}atthew {R}ocklin },
  title     = { {D}ask: {P}arallel {C}omputation with {B}locked algorithms and {T}ask {S}cheduling },
  booktitle = { {P}roceedings of the 14th {P}ython in {S}cience {C}onference },
  pages     = { 126 - 132 },
  year      = { 2015 },
  editor    = { {K}athryn {H}uff and {J}ames {B}ergstra },
  doi       = { 10.25080/Majora-7b98e3ed-013 }
}

```

**Comment by timothyas** [comment]
Regarding the Lorenz, 1996 citation, I saw that suggestion, but I don't think it's correct. I also don't have access to that reference, so I'm not sure. This citation is from a conference and is highly cited, but the way that it's cited varies a lot between publications. The citation I gave is the best one that I can come up with unfortunately (it's the one our group has been using).

As for the dask citation, that's interesting. They used to list the citation I gave on their documentation page as "How to Cite", but I don't see that anymore... I'll add the citation you listed as well just to cover my bases here.

**Comment by sneakers-the-rat** [comment]
> I don't think it's correct.

Got it! you know better than me.

> I don't see that anymore

odd... well when in doubt you can double-cite: citations are free to make and costly (to the cited authors) to miss. neutral on this change, either/or works for me.

feel free to close this once you merge #80

**Comment by timothyas** [comment]
Strong agree: it's easy to cite, but is a shame not to be appropriately cited. I added both dask citations in the text.
